version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.lo-mercat
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  adminjs:
    build:
      context: .
      dockerfile: Dockerfile.adminjs
    depends_on:
      - postgres
    ports:
      - "3001:3000"
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
