version: "3.3"
services:
  adminjs:
    build:
      context: .
      dockerfile: Dockerfile.adminjs
    depends_on:
      - db
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/initdb
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    ports:
      - "5432:5432"
